#include        "Script.hh"

std::map<std::string, Script::ParamReader> Script::_readers = {
  {"byte", &Script::_readByte},
  {"word", &Script::_readWord},
  {"dword", &Script::_readDword},
  {"ptr", &Script::_readPointer},
  {"var", &Script::_readVariable},
  {"flag", &Script::_readFlag},
  {"bank", &Script::_readBank},
  {"buff", &Script::_readBuffer},
  {"buffer", &Script::_readBuffer},
  {"hidden", &Script::_readHiddenVar},
  {"ptr/bank", &Script::_readPtrOrBank},
  {"ptr/bank0", &Script::_readPtrOrBank0},
  {"flag/var", &Script::_readFlagOrVar},
  {"word/var", &Script::_readWordOrVar},
  {"byte/var", &Script::_readByteOrVar},

  {"b", &Script::_readByte},
  {"w", &Script::_readWord},
  {"d", &Script::_readDword},
  {"dw", &Script::_readDword},
  {"p", &Script::_readPointer},
  {"v", &Script::_readVariable},
  {"f", &Script::_readFlag},
  {"bk", &Script::_readBank},
  {"bf", &Script::_readBuffer},
  {"h", &Script::_readHiddenVar},
  {"p/bk", &Script::_readPtrOrBank},
  {"p/bk0", &Script::_readPtrOrBank0},
  {"f/v", &Script::_readFlagOrVar},
  {"w/v", &Script::_readWordOrVar},
  {"b/v", &Script::_readByteOrVar}
};
